services:
  web-server:
    image: nginx:1.21.1
    container_name: webdev-nginx
    ports:
      - "80:80"
    volumes:
      - ./volumes/servers/:/etc/nginx/conf.d/
      - ./volumes/ssl:/var/www/ssl
      - ./wb-cms:/var/www/projects

  php:
    build:
      dockerfile: ./php.dockerfile
      context: .
    image: php:8.1-fpm
    container_name: webdev-php
    volumes:
      - ./wb-cms:/var/www/projects
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0.33
    container_name: webdev-mysql
    volumes:
      - ./volumes/mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weirdbird
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webdev-phpmyadmin
    volumes:
      - ./volumes/phpmyadmin:/etc/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    links:
      - db
